# Este archivo es el punto de entrada de la configuración de servicios del módulo.
# https://symfony.com/doc/current/service_container.html

services:
  # Configuración por defecto para los servicios en este módulo
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $projectDir: '%kernel.project_dir%'

  # Hace que las clases de este namespace estén disponibles como servicios.
  App\Bundles\pqr\:
    resource: '../../*'
    exclude:
      - '../../Resources/'
      - '../../templates/'
      - '../../translations/'
      - '../../formatos/'
      - '../../helpers/'
      - '../../Services/'

imports:
  - { resource: "./migrations.yaml" }
